import { SiteSettings } from "../types";
import { AdminUser, DashboardData } from "../types";


export const dummyUser: AdminUser = {
  name: "J. Smith",
  email: "j.smith@lmcs.com",
  role: "Executive Admin",
};

export const dummyDashboardData: DashboardData = {
  stats: [
    {
      id: "published-pages",
      label: "Published Pages",
      value: 42,
      delta: "+8.2%",
      trend: "up",
      detail: "Compared with last month",
    },
    {
      id: "draft-pages",
      label: "Draft Pages",
      value: 12,
      delta: "+2",
      trend: "up",
      detail: "Since last week",
    },
    {
      id: "hidden-pages",
      label: "Hidden Pages",
      value: 3,
      delta: "-1",
      trend: "down",
      detail: "Compared with last month",
    },
    {
      id: "published-insights",
      label: "Published Insights",
      value: 128,
      delta: "+12.5%",
      trend: "up",
      detail: "Compared with last month",
    },
    {
      id: "draft-insights",
      label: "Draft Insights",
      value: 5,
      delta: "0",
      trend: "flat",
      detail: "No change this week",
    },
  ],

  recentChanges: {
    data: [
      {
        id: "1",
        title: "Strategic Overview",
        type: "Page",
        status: "published",
        action: "Published",
        updatedAt: "2 hours ago",
        updatedBy: "J. Smith",
        summary: "Updated the strategic overview content and published it.",
      },
      {
        id: "2",
        title: "Project Drift Analysis",
        type: "Insight",
        status: "draft",
        action: "Updated",
        updatedAt: "4 hours ago",
        updatedBy: "S. Reed",
        summary: "Added new findings and updated project analysis.",
      },
      {
        id: "3",
        title: "Terms of Engagement",
        type: "Legal",
        status: "published",
        action: "Updated",
        updatedAt: "Yesterday",
        updatedBy: "J. Smith",
        summary: "Updated the legal terms and engagement policy.",
      },
      {
        id: "4",
        title: "Leadership Bio: CEO",
        type: "Page",
        status: "hidden",
        action: "Archived",
        updatedAt: "2 days ago",
        updatedBy: "A. Chen",
        summary: "Temporarily hidden the CEO leadership profile.",
      },
      {
        id: "5",
        title: "Market Expansion Strategy",
        type: "Report",
        status: "published",
        action: "Published",
        updatedAt: "3 days ago",
        updatedBy: "J. Smith",
        summary: "Published the latest market expansion strategy report.",
      },
      {
        id: "6",
        title: "Digital Transformation",
        type: "Insight",
        status: "draft",
        action: "Drafted",
        updatedAt: "4 days ago",
        updatedBy: "M. Carter",
        summary: "Created a new draft for the digital transformation insight.",
      },
      {
        id: "7",
        title: "Operational Excellence",
        type: "Page",
        status: "published",
        action: "Updated",
        updatedAt: "5 days ago",
        updatedBy: "S. Reed",
        summary: "Refined operational excellence page content.",
      },
      {
        id: "8",
        title: "Risk Management Framework",
        type: "Report",
        status: "published",
        action: "Published",
        updatedAt: "6 days ago",
        updatedBy: "A. Chen",
        summary: "Published the updated risk management framework.",
      },
      {
        id: "9",
        title: "Client Success Strategy",
        type: "Case Study",
        status: "draft",
        action: "Updated",
        updatedAt: "1 week ago",
        updatedBy: "J. Smith",
        summary: "Added new client success metrics and outcomes.",
      },
      {
        id: "10",
        title: "Leadership Principles",
        type: "Page",
        status: "published",
        action: "Updated",
        updatedAt: "1 week ago",
        updatedBy: "M. Carter",
        summary: "Updated leadership principles and supporting content.",
      },
      {
        id: "11",
        title: "Growth Opportunities",
        type: "Insight",
        status: "published",
        action: "Published",
        updatedAt: "8 days ago",
        updatedBy: "S. Reed",
        summary: "Published new insights about growth opportunities.",
      },
      {
        id: "12",
        title: "Corporate Governance",
        type: "Legal",
        status: "archived",
        action: "Archived",
        updatedAt: "9 days ago",
        updatedBy: "A. Chen",
        summary: "Archived the previous corporate governance document.",
      },
      {
        id: "13",
        title: "Annual Performance Review",
        type: "Report",
        status: "published",
        action: "Published",
        updatedAt: "10 days ago",
        updatedBy: "J. Smith",
        summary: "Published the annual performance review report.",
      },
      {
        id: "14",
        title: "Innovation Framework",
        type: "Insight",
        status: "draft",
        action: "Drafted",
        updatedAt: "11 days ago",
        updatedBy: "M. Carter",
        summary: "Started a new innovation framework insight.",
      },
      {
        id: "15",
        title: "Company History",
        type: "Page",
        status: "published",
        action: "Updated",
        updatedAt: "12 days ago",
        updatedBy: "S. Reed",
        summary: "Updated company history and milestones.",
      },
      {
        id: "16",
        title: "Sustainability Report",
        type: "Report",
        status: "published",
        action: "Published",
        updatedAt: "2 weeks ago",
        updatedBy: "J. Smith",
        summary: "Published the latest sustainability report.",
      },
      {
        id: "17",
        title: "Future Vision",
        type: "Page",
        status: "draft",
        action: "Drafted",
        updatedAt: "2 weeks ago",
        updatedBy: "A. Chen",
        summary: "Created the initial draft for the future vision page.",
      },
      {
        id: "18",
        title: "Strategic Priorities",
        type: "Insight",
        status: "published",
        action: "Updated",
        updatedAt: "2 weeks ago",
        updatedBy: "M. Carter",
        summary: "Updated strategic priorities and key objectives.",
      },
    ],

    pagination: {
      page: 1,
      limit: 10,
      total: 18,
      totalPages: 2,
    },
  },
};

export const dummySettings: SiteSettings = {
  websiteName: "LMCS Corporate Portal",
  websiteStatus: "Active",
  defaultContentVisibility: "Public",
  unreleasedContent: "Hidden from Public",
  publicContactEmail: "admin@lmcs.com",
  publicPhone: "+1 (555) 019-2837",
};